const mutationTypes = {
  UPDATE_ISSHOWSEARCH: 'UPDATE_ISSHOWSEARCH',
  UPDATE_SEARCHWORDS: 'UPDATE_SEARCHWORDS',
  UPDATE_EDITMACHINEINFO: 'UPDATE_EDITMACHINEINFO',
  UPDATE_ADDNEWMACHINECOUNT: 'UPDATE_ADDNEWMACHINECOUNT'
};
export default mutationTypes;