const mutationTypes = {
  UPDATE_LOGININFO: 'UPDATE_LOGININFO',
  UPDATE_SHOWDISMISSIBLEALERT: 'UPDATE_SHOWDISMISSIBLEALERT',
  UPDATE_ISSHOWSEARCH: 'UPDATE_ISSHOWSEARCH',
  UPDATE_SEARCHWORDS: 'UPDATE_SEARCHWORDS'
};
export default mutationTypes;